const express= require ('express');
const router = express.Router();
const usersController= require('../controllers/usersController');
const { validate } = require('../middlewares/validators');
const checkAuthMiddleware= require('../middlewares/jwt_token');
router.get('/',checkAuthMiddleware.checkAccessToken,usersController.get);
router.get('/all-paging',checkAuthMiddleware.checkAccessToken,usersController.getallpaging);
router.get('/roles',checkAuthMiddleware.checkAccessToken,usersController.getRoles);
router.get('/address',checkAuthMiddleware.checkAccessToken,usersController.getListAddress);
router.get('/address/:id',checkAuthMiddleware.checkAccessToken,usersController.getAddress);
router.get('/bookings',checkAuthMiddleware.checkAccessToken,usersController.getListBooking);
router.get('/bookings/:id',checkAuthMiddleware.checkAccessToken,usersController.getBooking);
router.get('/stores',checkAuthMiddleware.checkAccessToken,usersController.getListStore);
router.get('/stores/:id',checkAuthMiddleware.checkAccessToken,usersController.getStore);
router.get('/:id',checkAuthMiddleware.checkAccessToken,usersController.getbyID);
router.put('/:id',checkAuthMiddleware.checkAccessToken,usersController.update);
router.delete('/:id',checkAuthMiddleware.checkAccessToken,usersController.delete);
router.delete('/delete/:id',checkAuthMiddleware.checkAccessToken,usersController.destroy);
router.post('/register',usersController.register);  
router.post('/login',usersController.login);
router.get('/restore/:id',checkAuthMiddleware.checkAccessToken,usersController.restore);
// router.put('/reset-password/:id',usersController.resetpassword);

module.exports= router;